create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text unique not null,display_name text not null,avatar_url text,banner_url text,bio text default '',subscribers_count bigint not null default 0,created_at timestamptz not null default now());
create table if not exists public.videos(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,title text not null,description text default '',category text not null default 'Other',tags text[] not null default '{}',thumbnail_url text,video_url text,duration integer,orientation text not null default 'horizontal' check(orientation in('horizontal','vertical')),visibility text not null default 'public' check(visibility in('public','unlisted','private')),views_count bigint not null default 0,likes_count bigint not null default 0,dislikes_count bigint not null default 0,comments_count bigint not null default 0,created_at timestamptz not null default now());
create table if not exists public.comments(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,video_id uuid not null references public.videos(id) on delete cascade,parent_id uuid references public.comments(id) on delete cascade,body text not null,is_hidden boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.likes(user_id uuid not null references public.profiles(id) on delete cascade,video_id uuid not null references public.videos(id) on delete cascade,value smallint not null check(value in(-1,1)),primary key(user_id,video_id));
create table if not exists public.subscriptions(subscriber_id uuid not null references public.profiles(id) on delete cascade,creator_id uuid not null references public.profiles(id) on delete cascade,created_at timestamptz not null default now(),primary key(subscriber_id,creator_id),check(subscriber_id<>creator_id));
create table if not exists public.playlists(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,name text not null,description text default '',is_public boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.playlist_videos(playlist_id uuid not null references public.playlists(id) on delete cascade,video_id uuid not null references public.videos(id) on delete cascade,position integer not null default 0,primary key(playlist_id,video_id));
create table if not exists public.watch_history(user_id uuid not null references public.profiles(id) on delete cascade,video_id uuid not null references public.videos(id) on delete cascade,progress_seconds integer not null default 0,completed boolean not null default false,updated_at timestamptz not null default now(),primary key(user_id,video_id));
create table if not exists public.saved_videos(user_id uuid not null references public.profiles(id) on delete cascade,video_id uuid not null references public.videos(id) on delete cascade,created_at timestamptz not null default now(),primary key(user_id,video_id));
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,type text not null,title text not null,body text not null,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.reports(id uuid primary key default gen_random_uuid(),reporter_id uuid not null references public.profiles(id) on delete cascade,video_id uuid references public.videos(id) on delete cascade,comment_id uuid references public.comments(id) on delete cascade,reported_user_id uuid references public.profiles(id) on delete cascade,reason text not null,status text not null default 'open',created_at timestamptz not null default now());
alter table public.profiles enable row level security;
alter table public.videos enable row level security;
alter table public.comments enable row level security;
alter table public.likes enable row level security;
alter table public.subscriptions enable row level security;
alter table public.playlists enable row level security;
alter table public.playlist_videos enable row level security;
alter table public.watch_history enable row level security;
alter table public.saved_videos enable row level security;
alter table public.notifications enable row level security;
alter table public.reports enable row level security;
create policy "profiles readable" on public.profiles for select using(true);
create policy "own profile insert" on public.profiles for insert to authenticated with check(auth.uid()=id);
create policy "own profile update" on public.profiles for update to authenticated using(auth.uid()=id) with check(auth.uid()=id);
create policy "public videos readable" on public.videos for select using(visibility='public' or auth.uid()=user_id);
create policy "own videos insert" on public.videos for insert to authenticated with check(auth.uid()=user_id);
create policy "own videos update" on public.videos for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own videos delete" on public.videos for delete to authenticated using(auth.uid()=user_id);
create policy "comments readable" on public.comments for select using(is_hidden=false);
create policy "comments insert own" on public.comments for insert to authenticated with check(auth.uid()=user_id);
create policy "comments delete own" on public.comments for delete to authenticated using(auth.uid()=user_id);
create policy "likes readable" on public.likes for select using(true);
create policy "likes own" on public.likes for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "subscriptions readable" on public.subscriptions for select using(true);
create policy "subscriptions own" on public.subscriptions for all to authenticated using(auth.uid()=subscriber_id) with check(auth.uid()=subscriber_id);
create policy "playlists readable" on public.playlists for select using(is_public or auth.uid()=user_id);
create policy "playlists own" on public.playlists for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "history own" on public.watch_history for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "saved own" on public.saved_videos for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "notifications own" on public.notifications for select to authenticated using(auth.uid()=user_id);
create policy "reports insert" on public.reports for insert to authenticated with check(auth.uid()=reporter_id);
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
